server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cu_bank
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

jwt:
  secret: (G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2r5u8x/
  expiry: 30